### ISSUE TITLE
Cannot launch the IntuneMAMPackager on MacOS 10.14.6

### ISSUE THREAD

**Issue by pedrr** [msintuneappsdk/intune-app-wrapping-tool-ios#31]
if I download the latest one 12.0.12 I cannot launch the IntuneMAMPackager on MacOS 10.14.6 with the following error message from the OS:

####
"IntuneMAMPackager" is damaged and can't be opened. You should move it to the Trash.
####

![image](https://user-images.githubusercontent.com/10165399/66478574-0074dd00-ea9b-11e9-8659-f4b992de782b.png)

**Comment by Kyle-Reis** [comment]
Hey @pedrr, you should first launch a terminal window, then drag/drop the IntuneMAMPackager file into the terminal to paste in the full path to the executable

**Comment by Kyle-Reis** [comment]
https://docs.microsoft.com/intune/developer/app-wrapper-prepare-ios#run-the-app-wrapping-tool

**Comment by pedrr** [comment]
ok, it works in this way, but what causes this change? As I remember correctly, with SDK 10.X it works with opening it from the finder

**Comment by Kyle-Reis** [comment]
Why do you want to open from Finder? You will need to provide command line arguments to use the tool.

**Comment by cjennewein-uhi** [comment]
I receive the same error when using the IntuneMAMPackager in Terminal with MacOS 10.15.

I mount the dmg and run the command, then immediately receive the error.
`/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i app.ipa -o app_intune.ipa -p app.mobileprovision -c "cert_name" -v`
`zsh: killed     /Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i  -o  -p  -c  -`

**Comment by Kyle-Reis** [comment]
@cjennewein-uhi, I am also able to reproduce this and am investigating.

**Comment by ram2386** [comment]
@Kyle-Reis: I am getting the same error message in the IntuneMAMPackager in Terminal with MacOS 10.15.

<img width="1191" alt="Screenshot 2019-10-20 at 2 17 58 PM" src="https://user-images.githubusercontent.com/217577/67157077-794e2180-f344-11e9-854e-06694eace932.png">

Please find the above-attached screenshot for the same.

**Comment by Kyle-Reis** [comment]
Hey @pedrr, @cjennewein-uhi, and @ram2386. We just pushed an update to the repo which should address this issue. Could you each confirm that it's working for you now?

**Comment by cjennewein-uhi** [comment]
@Kyle-Reis, I can confirm I was able to package the app after the dmg update. Thanks!

**Comment by taofang0418** [comment]
@Kyle-Reis I still have the same problem with version 12.0.12 on MacOS 10.15

**Comment by ram2386** [comment]
@Kyle-Reis I still have the same problem on MacOS 10.15 and getting the same error message.

**Comment by Kyle-Reis** [comment]
Hey @taofang0418, and @ram2386, I was able to reproduce the issue as well after downloading the source zip from the [releases page](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases). Could you confirm that this is how you downloaded the DMG? As a workaround, if you clone the git repo, it should work. I'll continue to investigate in the meantime

**Comment by ram2386** [comment]
Thank you @Kyle-Reis, Yes if I clone the git repo, it works. Please let me know once you resolve the issue when I download and install it via the source zip.

**Comment by Kyle-Reis** [comment]
We'll have an update out soon which should address the source-download issue.

**Comment by taofang0418** [comment]
Hi @Kyle-Reis , it was not working by downloading the source zip but works with clone the git repo.

**Comment by Kyle-Reis** [comment]
Hey everyone. This issue should be addressed with today's update. Note: we had to move the plist argument example file out of the .DMG and into the repo root. It should be included in the DMG again with the next update.

**Comment by ram2386** [comment]
@Kyle-Reis: I am getting the same error message in the IntuneMAMPackager in Terminal with MacOS 10.15 while installed the latest source file. 

Please find the attached screenshot for your reference.

<img width="1151" alt="Screenshot 2019-11-05 at 3 45 18 PM" src="https://user-images.githubusercontent.com/217577/68199244-ac024600-ffe3-11e9-87eb-08472a323ae3.png">

**Comment by ericschrad1987** [comment]
Hi Everyone. I downloaded the latest release and am getting the same error as the original poster. I have tried copying the path to terminal and running the script through terminal with no success. 

What can I do?

**Comment by Trhacz** [comment]
I have same problem.
